name: blott_asessment
description: "A new Flutter project for an Assessment"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.0-248.0.dev <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  url_launcher: ^6.3.0
  shared_preferences: ^2.2.3
  flutter_svg: ^2.0.10+1
  cupertino_icons: ^1.0.6
  awesome_notifications: ^0.9.3+1
  awesome_notifications_core: ^0.9.3
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
     - assets/
